import {ExternalLink,Globe2,LockKeyhole,MapPin,Phone} from 'lucide-react';
import type {Store,Vehicle} from './types';
import {money} from './logic';

const updated=(store:Store)=>new Date(store.lastUpdated).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'});

export function PublicCommand({store,setPage}:{store:Store;setPage:(page:string)=>void}){
  const advertised=store.vehicles.reduce((sum,v)=>sum+v.price,0);
  const makes=new Set(store.vehicles.map(v=>v.make)).size;
  const newest=Math.max(...store.vehicles.map(v=>v.year));
  const oldest=Math.min(...store.vehicles.map(v=>v.year));
  const low=[...store.vehicles].sort((a,b)=>a.price-b.price)[0];
  const high=[...store.vehicles].sort((a,b)=>b.price-a.price)[0];
  const recent=[...store.vehicles].sort((a,b)=>b.year-a.year||a.mileage-b.mileage).slice(0,7);
  return <div className="command public-command"><section className="command-head"><div><p className="command-date">LIVE PUBLIC INVENTORY · {updated(store)}</p><h1>Current inventory.</h1><p>Verified from Lemaster Motorcars' public Dealer.com listings. Private DMS, CRM, cost, market-comparison, and lead data are not connected.</p></div><div className="day-tape"><div><span>IN STOCK</span><b>{store.vehicles.length}</b></div><div><span>ADVERTISED VALUE</span><b>{money(advertised)}</b></div><div><span>MAKES</span><b>{makes}</b></div><div><span>MODEL YEARS</span><b>{oldest}–{newest}</b></div></div></section><section className="ops-layout"><div className="queue"><div className="queue-head"><div><h2>Public inventory book</h2><p>Current advertised vehicles, ordered by newest model year</p></div><button onClick={()=>setPage('Inventory')}>View all inventory</button></div>{recent.map((v,i)=><a className="public-queue-row" key={v.id} href={v.listingUrl} target="_blank" rel="noreferrer"><div className="queue-rank">{String(i+1).padStart(2,'0')}</div><div className="queue-object"><span>STOCK {v.id} · {v.status.toUpperCase()}</span><h3>{v.year} {v.make} {v.model}</h3><p>{v.trim}</p></div><div className="queue-facts"><span>{v.mileage.toLocaleString()} miles</span><span>{v.drivetrain||'Drivetrain not listed'}</span><span>{v.color||'Color not listed'}</span></div><div className="public-price"><small>ADVERTISED PRICE</small><b>{money(v.price)}</b><span>{v.transmission}</span></div><ExternalLink size={17}/></a>)}</div><aside className="ops-rail"><section><h3>Published range</h3><b>{money(low.price)}</b><p>Lowest advertised vehicle: {low.year} {low.make} {low.model}.</p><div className="range-high">High <strong>{money(high.price)}</strong><small>{high.year} {high.make} {high.model}</small></div></section><section className="dealer-facts"><h3>Dealership</h3><p><MapPin size={15}/>{store.dealership?.address}</p><p><Phone size={15}/>{store.dealership?.phone}</p><p><Globe2 size={15}/><a href={store.sourceUrl} target="_blank" rel="noreferrer">lemastermotorcars.com</a></p></section><section><h3>Data boundary</h3><p>This public-data demo never infers private costs, leads, days owned, market position, or employee activity.</p></section></aside></section></div>
}

export function PublicInventory({store,query}:{store:Store;query:string}){
  const rows=store.vehicles.filter(v=>`${v.year} ${v.make} ${v.model} ${v.trim} ${v.id} ${v.vin}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="page-intro inventory-intro"><div><span className="section-code">LIVE / PUBLIC INVENTORY</span><h2>Inventory book</h2><p>{rows.length} of {store.vehicles.length} current listings · verified {updated(store)}</p></div><a className="primary" href={store.sourceUrl} target="_blank" rel="noreferrer">Dealer website <ExternalLink size={15}/></a></div><div className="inventory-strip"><span><b>{store.vehicles.length}</b> in stock</span><span><b>{new Set(store.vehicles.map(v=>v.make)).size}</b> makes</span><span><b>{money(store.vehicles.reduce((a,v)=>a+v.price,0))}</b> advertised value</span><span><b>$994</b> published documentation fee</span></div><div className="data-table inventory-table public-table"><table><thead><tr><th>Vehicle / stock</th><th className="num">Advertised price</th><th className="num">Mileage</th><th>Color</th><th>Drivetrain</th><th>Transmission</th><th>VIN</th><th/></tr></thead><tbody>{rows.map(v=><tr key={v.id}><td><span className="health-dot healthy"/><div><b>{v.year} {v.make} {v.model}</b><small>{v.trim} · <code>{v.id}</code></small></div></td><td className="num"><b>{money(v.price)}</b><small>plus published fees</small></td><td className="num"><b>{v.mileage.toLocaleString()}</b><small>miles</small></td><td>{v.color||'Not published'}</td><td><b>{v.drivetrain||'—'}</b></td><td>{v.transmission||'Not published'}</td><td><code>{v.vin}</code></td><td><a href={v.listingUrl} target="_blank" rel="noreferrer" aria-label={`Open ${v.year} ${v.make} ${v.model}`}><ExternalLink size={16}/></a></td></tr>)}</tbody></table></div></>
}

export function PrivateDataUnavailable({area}:{area:string}){return <section className="unavailable"><LockKeyhole size={28}/><span className="section-code">PRIVATE DEALERSHIP DATA</span><h2>{area} is not connected.</h2><p>The public website does not expose the internal data required for this workspace. Connect the dealership's DMS, CRM, market-data, and auction sources to use real operational information here.</p><div><span>Not fabricated</span><b>No placeholder leads, costs, deal figures, auction candidates, or performance metrics are shown.</b></div></section>}
